/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ondecomi.view;
import dao.AvaliadorDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ondecomi.model.*;


/**
 *
 * @author Luan Amor
 */
public class TelaLogin extends javax.swing.JFrame {
    Avaliadores enviarDados;
   // Avaliador ava;
    private String teste;
    ArrayList<Avaliador> avaliadores = new ArrayList();
    AvaliadorDao novo = new AvaliadorDao();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvaliadores = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        areaTrb2 = new javax.swing.JDesktopPane();
        btnSelecionaAvaliador1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNovoAvaliador1 = new javax.swing.JButton();
        btnSelecionaAvaliador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNovoAvaliador = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        btnAvaliadores.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnAvaliadores.setText("Avaliadores");

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Acesso");
        jFrame1.setResizable(false);

        btnSelecionaAvaliador1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSelecionaAvaliador1.setText("Avaliador");
        btnSelecionaAvaliador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaAvaliador1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 48)); // NOI18N
        jLabel3.setText("Onde Comi?");

        btnNovoAvaliador1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnNovoAvaliador1.setText("Novo Avaliador");
        btnNovoAvaliador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAvaliador1ActionPerformed(evt);
            }
        });

        areaTrb2.setLayer(btnSelecionaAvaliador1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb2.setLayer(btnNovoAvaliador1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaTrb2Layout = new javax.swing.GroupLayout(areaTrb2);
        areaTrb2.setLayout(areaTrb2Layout);
        areaTrb2Layout.setHorizontalGroup(
            areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaTrb2Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(areaTrb2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionaAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        areaTrb2Layout.setVerticalGroup(
            areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTrb2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(93, 93, 93)
                .addComponent(btnSelecionaAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnNovoAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(areaTrb2)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrb2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);

        btnSelecionaAvaliador.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSelecionaAvaliador.setText("Avaliador");
        btnSelecionaAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaAvaliadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 48)); // NOI18N
        jLabel2.setText("Onde Comi?");

        btnNovoAvaliador.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnNovoAvaliador.setText("Novo Avaliador");
        btnNovoAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAvaliadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionaAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(btnSelecionaAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnNovoAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAvaliadorActionPerformed
        AvaliadorDao n = new AvaliadorDao();
        Avaliador ava = new Avaliador(JOptionPane.showInputDialog("Informe o nome do Avaliador"));
        n.addAvaliador(ava);
    }//GEN-LAST:event_btnNovoAvaliadorActionPerformed

    private void btnSelecionaAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaAvaliadorActionPerformed
        enviarDados = new Avaliadores();
        enviarDados.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSelecionaAvaliadorActionPerformed

    private void btnSelecionaAvaliador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaAvaliador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecionaAvaliador1ActionPerformed

    private void btnNovoAvaliador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAvaliador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoAvaliador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrb2;
    private javax.swing.JButton btnAvaliadores;
    private javax.swing.JButton btnNovoAvaliador;
    private javax.swing.JButton btnNovoAvaliador1;
    private javax.swing.JButton btnSelecionaAvaliador;
    private javax.swing.JButton btnSelecionaAvaliador1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
