/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ondecomi.view;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ondecomi.model.*;
/**
 *
 * @author Luan Amor
 */
public class TelaLogin extends javax.swing.JFrame {
    Avaliadores enviarDados;
    Avaliador ava;
    private String teste;
    ArrayList<Avaliador> avaliadores = new ArrayList(); 
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvaliadores = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        areaTrb1 = new javax.swing.JDesktopPane();
        btnSelecionaAvaliador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNovoAvaliador = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        btnAvaliadores.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnAvaliadores.setText("Avaliadores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso");
        setResizable(false);

        btnSelecionaAvaliador.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSelecionaAvaliador.setText("Avaliador");
        btnSelecionaAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaAvaliadorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 48)); // NOI18N
        jLabel2.setText("Onde Comi?");

        btnNovoAvaliador.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnNovoAvaliador.setText("Novo Avaliador");
        btnNovoAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAvaliadorActionPerformed(evt);
            }
        });

        areaTrb1.setLayer(btnSelecionaAvaliador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb1.setLayer(btnNovoAvaliador, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout areaTrb1Layout = new javax.swing.GroupLayout(areaTrb1);
        areaTrb1.setLayout(areaTrb1Layout);
        areaTrb1Layout.setHorizontalGroup(
            areaTrb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaTrb1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(areaTrb1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(areaTrb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionaAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        areaTrb1Layout.setVerticalGroup(
            areaTrb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTrb1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addComponent(btnSelecionaAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnNovoAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areaTrb1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrb1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionaAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaAvaliadorActionPerformed
            enviarDados = new Avaliadores();
            enviarDados.recebendo(teste);
            enviarDados.setVisible(true);
            dispose();
        /*NovosAvaliadores av = new NovosAvaliadores();
        areaTrb1.add(av);
        av.setVisible(true);*/
    }//GEN-LAST:event_btnSelecionaAvaliadorActionPerformed

    private void btnNovoAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAvaliadorActionPerformed
        //Cadastrando novos avaliadores
        //ava = new Avaliador(JOptionPane.showInputDialog(btnNovoAvaliador,"Digite seu nome"));
        teste = (JOptionPane.showInputDialog(btnNovoAvaliador,"Digite seu nome"));
        //avaliadores.add(ava);
    }//GEN-LAST:event_btnNovoAvaliadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrb1;
    private javax.swing.JButton btnAvaliadores;
    private javax.swing.JButton btnNovoAvaliador;
    private javax.swing.JButton btnSelecionaAvaliador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
